apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: k8sapp-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "k8sapp.myns.svc.cluster.local"

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: k8sapp-gateway-routes-rules
spec:
  host: k8sapp-service
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: k8sapp-gateway-routes
spec:
  hosts:
  - "k8sapp.myns.svc.cluster.local"
  gateways:
  - k8sapp-gateway  # binds routes to gateway above
  - mesh
  http:
  - route:
    - destination:
        port:
          number: 8080
        host: k8sapp-service
        subset: v1
      wegith: 50
    - destination:
        port:
          number: 8080
        host: k8sapp-service
        subset: v2
      weight: 50

