apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sapp-deployment
  labels:
    app: k8sapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8sapp
  template:
    metadata:
      labels:
        app: k8sapp
    spec:
      containers:
      - name: k8sapp
        image: haybu/k8s-app:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        env:
        - name: VERSION
          value: '1.1'
        ports:
        - containerPort: 8080