apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sapp-deployment-v1
  labels:
    app: k8sapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8sapp
      version: v1
  template:
    metadata:
      labels:
        app: k8sapp
        version: v1
    spec:
      containers:
      - name: k8sapp
        image: haybu/k8s-app:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        env:
        - name: VERSION
          value: '1'
        ports:
        - containerPort: 8080