apiVersion: v1
kind: Service
metadata:
  name: k8sapp-service
  labels:
    app: k8sapp
spec:
  selector:
    app: k8sapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http-port